### ISSUE TITLE
xenoData / anyElement messed up during ODD chaining

### ISSUE THREAD

**Issue by bansp** [TEIC/Stylesheets#245] opened 2017-03-16 13:08 UTC
[xenoData_test.tar.gz](https://github.com/TEIC/Stylesheets/files/847724/xenoData_test.tar.gz)

The above test case was made with the current Stylesheets and against the online p5subset.xml (where applicable).

I took tei_all and derived tei_all.rng from it (with `teitorelaxng`). 
Then I derived tei_all.compiled.xml from it (with `teitoodd`)
Then I copied tei_all.xml into tei_all_2nd.xml, and added a `source="tei_all.compiled.xml"` as the only change.
Then I derived tei_all_2nd.rng from tei_all_2nd.xml (with `teitorelaxng`). 

You can see the differences already by diffing the RNG documents.
I attach a little test.xml file, where you can change the xml-model PIs to see that the xenoData gets flagged as an error when used with tei_all_2nd.rng.

(I'd say it's a release blocker, but I don't want to slap the label myself without a countercheck)

**Comment by lb42** [comment] 2017-03-17 13:57
This seems a rather curious procedure. What were you hoping to achieve? If it is just to prove that using a compiled version of TEI all as a source is not a good idea, I agree. It's redundant since compiling your ODD with reference to the current source should do the same thing. But because we have to convert declarations for anyElement into something a bit different from other element declarations, it doesn't quite behave as you might expect. But why would you ever want to do this? 

Your test document is valid against TEI All. What's the problem you're trying to solve?

**Comment by bansp** [comment] 2017-03-17 14:28
**Observation:** in a document based on a schema derived by chaining, you (apparently) can't use `<xenoData>`

**Test attempt:** I was looking for something as close to an "identity transform" as I could get, in order to eliminate the possibility that something in the chaining ODD interferes with the definition of `<xenoData>` in some way.
I was hoping that chaining from TEI_all by keeping all the modules, with no modification, would provide such a testing ground. (To quote Lou: "It's redundant since compiling your ODD with reference to the current source should do the same thing". Exactly, I was hoping to achieve boring redundancy, essentially identity, bar some minor details.)

**Result of the procedure:** (quoting Lou again) "because we have to convert declarations for anyElement into something a bit different from other element declarations, it doesn't quite behave as you might expect."

**Suspicion:** because of the magic happening to anyElement in the process of compilation, xenoData gets messed up. This suspicion seems to be borne out.

**Expected outcome:** _working_ xenoData in documents based on schemas derived by chaining.

**Test suite:** in the out-of-the-box form, the document will validate against the tei_all schema, because the RNG that it uses was derived from tei_all. If you change the PI at the top (essentially swap the comments), you will see that it fails to validate against the derived RNG. The point being that _the derived RNG is what counts_, because it is based on the chained ODD, in which we should be able to do all sorts of modifications (so that tei_all potentially becomes irrelevant).

**Half-welcome way to falsify my claim:** Please show me a document based on a chained ODD, in which xenoData works. I will be happy that there is a way to make it work (and somewhat embarrassed about having posted this ticket). I will also be unhappy because I will then have no idea and not even a suspicion of what is wrong in the document that I based on a chained ODD, in which document xenoData fails to validate.

**Comment by lb42** [comment] 2017-03-17 17:52
OK, I like a challenge. Herewith a zip containing feather.odd, feather-xeno.odd, and your original test file. Use oddtoodd to compile feather.odd into feather.compiled, and then generate a schema from feather-xeno. I do both within oXygen 18.1, and the resulting schema says that your test file is valid.
[feather.zip](https://github.com/TEIC/Stylesheets/files/851372/feather.zip)

**Comment by bansp** [comment] 2017-03-17 19:34
Ah, you are a treasure :-)
I'll have a look, thanks. I'm already half unhappy... (sigh!)

**Comment by bansp** [comment] 2017-03-17 20:16
I am left without a suspicion... I mean, the game is now to reduce the ODDs and see at which point the document stops bugging out...
Because it's not necessarily true that anyElement doesn't get messed up -- it's just true that it doesn't get messed up in compilation based on the feather-light setup. Trouble is that for the standoff ODD, we don't want to reduce too much up front. Siiigh. Thanks for your time, Lou!

But BTW, it would be great to have something like an identity transform for ODD compilation.

**Comment by bansp** [comment] 2017-03-17 20:43
(and the initial result is promising: when I replaced the content of the schemaSpec in tei_all_2nd with the content of the schemaSpec in feather-xeno, things became green! So it's something in the chaining ODD.

**Comment by bansp** [comment] 2017-03-17 21:38
One thing that bothers me is that if I change the following:

```xml
<moduleRef key="header" include="teiHeader fileDesc titleStmt sourceDesc publicationStmt 
          availability distributor revisionDesc change"/> 
<elementRef key="xenoData" source="tei:current"/> 
```

by eliminating the elementRef and adding xenoData to the "include" list (and even if I explicitly add `<moduleRef key="tagdocs"/>`, for anyElement), then it bugs out. 

In my schema, I added the elementRef and that almost changed the picture except that now I'm getting  the ^%&^$ "conflicting ID-types for attribute" bug. So I'm just going to resign from using xenoData altogether, it's costed waaay too much trouble and time.

**Comment by lb42** [comment] 2017-03-17 22:27
Assuming that you are doing this in the ODD file feather-xeno, which uses feather.compiled as its source, it's no wonder that this change causes it to "bug out". The xenoData element is not included in the source against which that ODD is being processed: you need to specify a source for the processor to find it.

**Comment by bansp** [comment] 2017-03-21 13:19
I don't know any longer. It was the last night before leaving, and I was hoping to pin the issue down, and was working in parralel, building up from your version and stripping down from tei_all. At some point, in the rich version, I hit the "ID attribute blah blah" message, instead of the one I reported above. And I think that at this point I decided to catch some sleep instead of grinding on (having posted to TEI-L a request for a hack that would replace the macro.anyXML hack).

I am ready to close this ticket, although I don't have a feeling that the issue has been solved (or that I found tools that would help me discover why it didn't get solved, other than the source itself, which I would be happy to trace, except that the knowledge that even Martin, who by my standards is an Overwizard, has problems understanding the source, makes me doubt if I could glean anything useful from it within a sensible portion of my lifetime).

What bothers me greatly there seems to be way to play a boring zero-outcome game, that is that there is no guarantee that if I use X.odd to create X.rng and then set up Y.odd that would essentially say "take everything out of X.odd.compiled, don't add your own stuff" and use that to create Y.rng, then X.rng will express the same grammar as Y.rng. I thought, naively, that this is what should be expected. It would be immensely helpful to get a hint in the documentation, for why this does not happen, simply to be able to pay attention to that while playing with ODD chaining or ODDs in general.

**Comment by hcayless** [comment] 2017-03-21 13:55
Don't close it. I'm pretty sure there's something screwy going on here. I just don't know what, yet.

**Comment by lb42** [comment] 2017-03-21 14:02
The crucial thing (which the doc needs to explain better) is that the declarations provided by a compiled ODD are *only* included in the output of an ODD referencing that compiled ODD if they are referenced or requested by the referencing ODD. It's an easy mistake to assume that referencing them via @source is enough to pull them in -- I know cos I've made it myself -- but it aint so. Referencing them just makes them available.

**Comment by hcayless** [comment] 2017-03-21 14:11
@lb42 Sure, but what I'm seeing in @bansp's example is that ODD compilation is doing the wrong thing with anyElement—acting as though the definition is missing, even though it isn't. I think that's a bug, and probably specifically an ODD chaining bug.

**Comment by lb42** [comment] 2017-03-21 15:15
I have tried to reproduce the problem with my feather example but failed to do so. So it's something strange about TEI All, maybe? Herewith a zip. feather2.odd includes xenoData, and feather.odd doesn't. Compiling them both generates exactly what you'd expect: the only differences are in the presence of declarations for xenoData. feather-xeno.odd specifies feather2.compiled as its source and requests xenoData: it works fine for me. feather-no-xeno.odd uses feather.compiled and doesn't request xenoData. It also works fine. QED.[feather.zip](https://github.com/TEIC/Stylesheets/files/858580/feather.zip)

**Comment by hcayless** [comment] 2017-03-27 18:35
Think I've identified and fixed the problem. If you can check it, @bansp, I'll close the ticket.

**Comment by bansp** [comment] 2017-03-28 07:40
Thanks, I'll give it a shot as soon as I'm settled back in the office (been travelling).

**Comment by bansp** [comment] 2017-03-29 09:00
Hi @hcayless , YES, it works! :-)
Thanks!

**Closed** 2017-03-29 09:50 UTC
