### ISSUE TITLE
faulty xsd generation from tei framework in oxygen

### ISSUE THREAD

**Issue by eduarddrenth** [TEIC/Stylesheets#255] opened 2017-04-04 13:27 UTC
Validation fails for a correct xml using an xsd generated by tei framework 6.1.1 in oxygen.

Generating the xsd using oxgarage results in successfull validation.

odd used: https://bitbucket.org/teibestpractices/linguistic-customization/raw/4c343f21ebc97caf2751d620cd5bd5af26ae0a67/src/main/resources/customization/tdb.odd

compiled dependency: https://bitbucket.org/teibestpractices/linguistic-customization/raw/4c343f21ebc97caf2751d620cd5bd5af26ae0a67/src/main/resources/customization/linguistic_attributes.odd.compiled

[1604Bildtboer.xml.zip](https://github.com/TEIC/Stylesheets/files/893263/1604Bildtboer.xml.zip)

Validation error:

System ID: /home/eduard/teidir/tdb.fryske-akademy.nl/Hollands/1604Bildtboer.xml
Main validation file: /home/eduard/teidir/tdb.fryske-akademy.nl/Hollands/1604Bildtboer.xml
Schema: /home/eduard/linguistic-customization/src/main/resources/customization/out/tdb.xsd
Engine name: Xerces
Severity: error
Description: cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://www.tei-c.org/ns/1.0":body}'. One of '{"http://www.tei-c.org/ns/1.0":model.global.meta, "http://www.tei-c.org/ns/1.0":model.milestoneLike, "http://www.tei-c.org/ns/1.0":note, "http://www.tei-c.org/ns/1.0":model.global.edit, "http://www.tei-c.org/ns/1.0":metamark}' is expected.
Start location: 23:145
End location: 23:153
URL: http://www.w3.org/TR/xmlschema-1/#cvc-complex-type

**Comment by eduarddrenth** [comment] 2017-04-04 13:43
Problem solved!

When choosing "TEI ODD to XML Schema" the path to the ant file is wrong:

~/.com.oxygenxml/extensions/v18.1/frameworks/http___www.tei_c.org_release_oxygen_updateSite.oxygen/tei/xml/tei/stylesheet/xsd/build-to.xml

After correcting this to:

~/Oxygen XML Editor 18/frameworks/tei/xml/tei/stylesheet/xsd/build-to.xml

everything works as expected!

**Comment by martindholmes** [comment] 2017-04-04 15:21
I think what you've done in making that change is to switch from using the installed plugin version of the Stylesheets to using the version distributed with Oxygen itself. If you have the plugin installed and working in other respects, but this transformation fails, then I think we do have a bug, so I'm going to reopen this.

**Comment by eduarddrenth** [comment] 2017-04-04 16:52
You may be right there, indeed I switched to the oxygen version, which works. Didn't realize that

**Comment by eduarddrenth** [comment] 2017-04-05 06:23
additional info:

```
eduard@eduard-X756UB:~$ diff .com.oxygenxml/extensions/v18.1/frameworks/http___www.tei_c.org_release_oxygen_updateSite.oxygen/tei/xml/tei/stylesheet/xsd/build-to.xml Oxygen\ XML\ Editor\ 18/frameworks/tei/xml/tei/stylesheet/xsd/build-to.xml 
43c43
<       <arg value="${outputFile}.tmp"/>
---
>       <arg value="${outputFile}"/>
46,49d45
<     <xslt force="yes" style="postprocess.xsl" in="${outputFile}.tmp" out="${outputFile}">
<       <factory name="net.sf.saxon.TransformerFactoryImpl"/>
<     </xslt>
<     <delete file="${outputFile}.tmp"/>

```

**Comment by martindholmes** [comment] 2017-04-05 12:32
I can confirm that the XSD generated in Oxygen using the bleeding edge plugin also throws this validation error when validating the test file. However, the error is thrown on an `<ab>` element which is the first child of `<body>`; the error is:

~~~~~
cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://www.tei-c.org/ns/1.0":body}'. One of '{"http://www.tei-c.org/ns/1.0":model.global.meta, "http://www.tei-c.org/ns/1.0":model.milestoneLike, "http://www.tei-c.org/ns/1.0":note, "http://www.tei-c.org/ns/1.0":model.global.edit, "http://www.tei-c.org/ns/1.0":metamark}' is expected.
~~~~~

`<ab>` is a member of model.pLike, which should be allowed in `<body>` through model.common. The linguistic_attributes.odd.compiled does rewrite the content model of `<body>`, but the revised content model still includes model.common, so I'm not sure what's happening here.

**Comment by eduarddrenth** [comment] 2017-04-05 16:19
For clarity: the step that generates the xsd fails when using the tei_c
variant. The compiled linguistic_attributes seems of no influence.

When I disable the postprocessing step like this (last lines of
build-to.xml):

      <arg value="${outputFile}"/>
    </java>
    <delete file="${outputFile}.rng"/>


validation succeeds again.

**Comment by martindholmes** [comment] 2017-04-05 16:59
@hcayless was working on postprocess.xsl in December; perhaps one of his changes triggers an unexpected side-effect.

**Comment by eduarddrenth** [comment] 2017-04-06 05:17
I see an improvment here:

  <xsl:template match="/">
    <xsl:apply-templates select="node()|comment()|processing-instruction()"/>
  </xsl:template>
  
  <xsl:template match="node()|@*|comment()|processing-instruction()">
    <xsl:copy>
      <xsl:apply-templates select="node()|@*|comment()|processing-instruction()"/>
    </xsl:copy>
  </xsl:template>

it should be replaced by (node() also matches comment and proc-instr, process atts first when applying):
  
  <xsl:template match="node()|@*">
    <xsl:copy>
      <xsl:apply-templates select="@*|node()"/>
    </xsl:copy>
  </xsl:template>

But this doesn't solve the problem.

When I leave out this template "<xsl:template match="xs:group[@ref]">", the problem disappears.

**Comment by eduarddrenth** [comment] 2017-04-06 06:32
additional (to prevent problems with template selection):

<xsl:template match="node()|@" priority="-1">
xsl:copy
<xsl:apply-templates select="@|node()"/>
</xsl:copy>
</xsl:template>

**Comment by martindholmes** [comment] 2017-04-06 12:09
I think @hcayless should look at this, since he's familiar with it. I also think it should be release-blocking, since it's a regression (previously worked, now broken), although the regression is from two versions ago.

**Comment by hcayless** [comment] 2017-07-04 18:44
Should be fixed. I tested the ODD and XML file posted by @eduarddrenth, and they work together now. There were a few cases postprocess.xsl wasn't handling correctly.

**Closed by hcayless** 2017-07-04 18:44 UTC
Labels: Release Blocker
