### ISSUE TITLE
TEI ODD to DTD fails

### ISSUE THREAD

**Issue by laurentromary** [TEIC/Stylesheets#346] opened 2018-11-30 16:17 UTC
For a legacy project still in activity (assistant staff using a basic editing environment using the said DTD), I maintain an (unsure...) ODD file from which I generate a DTD. The last compilation from 7 June 2018 worked and I now get the following error:

System ID: /Users/romary/Documents/Workbench/IFIPSpecifications/Specification/SpringerBook.xml
Scenario: TEI ODD to DTD
Build file: /Users/romary/Library/Preferences/com.oxygenxml/extensions/v20.1/frameworks/http___www.tei_c.org_release_oxygen_updateSite.oxygen/tei/xml/tei/stylesheet/dtd/build-to.xml
Document type: TEI ODD
Engine name: ANT
Severity: fatal
Description: Transformation failed. /Users/romary/Library/Preferences/com.oxygenxml/extensions/v20.1/frameworks/http___www.tei_c.org_release_oxygen_updateSite.oxygen/tei/xml/tei/stylesheet/common/teianttasks.xml:386: java.lang.NoClassDefFoundError: ro/sync/basic/util/Crypto

Is this something known? Is there an easy fix? Would it be solved if I switched to pure ODD (:-} 7000 lines of ODD to purify)?

**Comment by laurentromary** [comment] 2018-11-30 16:40
Following @martindholmes advice I have switched to HA and now get:


Transformation failed. /Users/romary/Library/Preferences/com.oxygenxml/extensions/v20.1/frameworks/http___www.tei_c.org_release_oxygen_updateSite.oxygen/tei/xml/tei/stylesheet/common/teianttasks.xml:386: java.lang.SecurityException: class "net.sf.saxon.jaxp.IdentityTransformer"'s signer information does not match signer information of other classes in the same package
--
Can this be an issue with the version I used (9-9-0-2)?

**Comment by martindholmes** [comment] 2018-12-14 16:50
@laurentromary You have two tickets with exactly the same heading (#345 and #346), and they seem to involve the same ODD file. Can this one be closed?

**Comment by peterstadler** [comment] 2019-09-16 11:48
seems like a duplicate of #345 which just got closed.

**Closed by peterstadler** 2019-09-16 11:48 UTC
