### ISSUE TITLE
The transformtei script does not always check the status of the commands it launches

### ISSUE THREAD

**Issue by lddubeau** [TEIC/Stylesheets#351] opened 2018-12-24 18:44 UTC
### Versions

```
$ teitoodd --help
TEI conversion: from tei to odd
[...]
Stylesheet family version: 7.46.0
```

```
$ apt-cache policy tei-xsl
tei-xsl:
  Installed: 7.46.0
  Candidate: 7.46.0
  Version table:
 *** 7.46.0 500
        500 https://packages.tei-c.org/deb/binary ./ Packages
        100 /var/lib/dpkg/status
```

### Steps to reproduce

1. Go into a new empty directory.

2. Execute `teitoodd myTEI.xml /tmp/non-existent-directory/foo.compiled; echo $?`. The `myTEI.xml` file just needs to be a valid customization of TEI. I just use a stock TEI exported from http://roma.tei-c.org/

### Actual Results

1. The command output says `BUILD SUCCESSFUL`, and the exit status (the last line of output) is 0:

```
$ teitoodd schemas/myTEI.xml /tmp/non-existent-directory/foo.compiled; echo $?
WARNING: No localsource set. Will get a copy from http://www.tei-c.org/Vault/P5/.
/usr/bin/teitoodd: 1: cd: can't cd to /tmp/non-existent-directory
Convert myTEI.xml to /home/ldd/src/git-repos/wed/packages/core/foo.compiled (tei to odd) using profile default
     [echo] Do ODD expand processing (schema ) 

BUILD SUCCESSFUL
Total time: 3 seconds
0
```

2. There is a file `foo.compiled` in the directory that was current when `teitoodd` was launched.

### Expected results

1. The whole thing should fail hard as soon as the the script fails to `cd` into the parent directory of the destination file. The script should moreover exit with a non-zero status.

2. There should not be any file generated anywhere. (I'm pretty sure implementing the previous point would automatically take care of this one too.)

### Observations

`transformtei` should turn on `set -e` early to avoid issues like the one I'm reporting, but using `set -e` may require other changes elsewhere in the script if there are places where it is legitimate to ignore errors.

**Comment by peterstadler** [comment] 2018-12-31 09:43
I agree that https://github.com/TEIC/Stylesheets/blob/fcd97d089de1bebd4e9c4e4356a9f694e302250d/bin/transformtei#L192 is too lazy and does not handle non-existent output directories properly. But was is the intended behaviour? Simply fail or rather create the directory? (I tend towards the latter …)

**Comment by lddubeau** [comment] 2019-01-09 12:23
So there are two issues:

1. What to do if the directory that should contain the output file does not exist? Create it? Fail?

2. The code should be tightened so that it does not default to ignoring failures of the commands it launches. (My suggestion to add `set -e` and maybe add code to explicitly ignore errors where doing so is warranted. )

Regarding the first issue, I don't see any consistency among the tools I use. Some will fail if the directory that should contain an output file does not exist prior to running the tool. Some will create the directory for me. I don't know of any rule of thumb that suggests one approach over the other.

I'd be inclined to go with automatic creation of the output directory.

**Comment by peterstadler** [comment] 2019-01-24 19:24
PR merged, closing the ticket

**Closed by peterstadler** 2019-01-24 19:24 UTC
Labels: CouncilResponsibility, bug, enhancement
