### ISSUE TITLE
classatts.xsl producing "internal" Saxon error

### ISSUE THREAD

**Issue by joeytakeda** [TEIC/Stylesheets#276] opened 2017-07-21 20:23 UTC
I'm using the bleeding edge TEI framework for oXygen to create an RNG from an ODD in an ANT build. Using oXygen and Saxon 9 HE, this line:

```
  <buildgeneric type="relaxng" xsl="${teiPlugin}/xml/tei/stylesheet/profiles/tei/relaxng/to.xsl" in="${odd.processed}" out="${schema}"/>
```
Produces this error:

``` 
*** Internal problem: Base value for indexed filter is not indexable (net.sf.saxon.expr.LetExpression)
[xslt]     Filter at line 155 of file:/home/netlink/jtakeda/.com.oxygenxml/extensions/v19.0/frameworks/http___teijenkins.hcmc.uvic.ca_job_oxygen_tei_bleeding_lastSuccessfulBuild_artifact_oxygen_tei_updateSite.oxygen/tei/xml/tei/stylesheet/odds/classatts.xsl 
 $Q{http://saxon.sf.net/generated-variable}loc1057468716[(data(attribute::attribute(Q{}ident))) = $Q{http://saxon.sf.net/generated-variable}loc785306763]
```
According to this post in the Saxon forum (https://saxonica.plan.io/boards/3/topics/6543), this problem is because of "a predicate of the form /*[name()=$x] where $x is empty." Following the advice in the forum, I've squashed the error messages locally by simply adding an `<xsl:if/>` to classatts.xsl like so:

```
  <xsl:variable name="attDefs" select=".//attDef"/>
<xsl:if test="not(empty($attDefs))">
        <xsl:for-each select="$attDefs">
          <encounter ident="{@ident}"/>
          <xsl:variable name="A" select="."/>
          <xsl:choose>
            <xsl:when test="$E//attDef[@ident = $A/@ident]">
              <override/>
              <xsl:for-each select="$E//attDef[@ident = $A/@ident]">
                <xsl:choose>
                  <xsl:when test="@mode = 'delete'"/>
                  <xsl:when test="not(@mode) or @mode = 'replace'">
                    <xsl:copy-of select="."/>
                  </xsl:when>
                  <xsl:otherwise>
                    <xsl:call-template name="mergeClassAttribute">
                      <xsl:with-param name="Old" select="$A"/>
                      <xsl:with-param name="New" select="."/>
                    </xsl:call-template>
                  </xsl:otherwise>
                </xsl:choose>
              </xsl:for-each>
            </xsl:when>
            <xsl:otherwise>
              <attRef class="{ancestor::classSpec/@ident}" name="{@ident}"/>
            </xsl:otherwise>
          </xsl:choose>
        </xsl:for-each>
      </xsl:if>
```
The result RNG seems unchanged by my modifications, but the ODD I'm working with is quite simple, so it might not be the best test case.

**Comment by sydb** [comment] 2017-07-21 21:12
I have to admit I did not read the > 2000 words of those forum posts thoroughly, but the take home message I got was not to add a conditional (which in theory should not do anything — if there are no descendant `<attDef>` nodes, then the `<xsl:for-each>` should never execute its children), but rather to upgrade the version of Saxon being executed.

What version of oXygen are you running?

**Comment by joeytakeda** [comment] 2017-07-21 21:50
I'm using oXygen 19.0.

And sure! This test ODD:

```
<TEI xmlns="http://www.tei-c.org/ns/1.0">
  <teiHeader>
      <fileDesc>
         <titleStmt>
            <title>Test ODD</title>
         </titleStmt>
         <publicationStmt>
            <p>For testing.</p>
         </publicationStmt>
         <sourceDesc>
            <p>Born digital for testing purposes.</p>
         </sourceDesc>
      </fileDesc>
  </teiHeader>
  <text>
      <body>
         <schemaSpec ident="myTEI">
            <moduleRef key="header"/>
            <moduleRef key="core"/>
            <moduleRef key="tei"/>
            <moduleRef key="textstructure"/> 
            
            <elementSpec ident="relatedItem" module="core" mode="change">
               <desc>identifies the document that these notes and apparatus apply.</desc>
               <attList>
                  <attDef ident="cert" mode="delete"/>
                  <attDef ident="corresp" mode="delete"/>
                  <attDef ident="facs" mode="delete"/>
                  <attDef ident="n" mode="delete"/>
                  <attDef ident="next" mode="delete"/>
                  <attDef ident="prev" mode="delete"/>
                  <attDef ident="style" mode="delete"/>
                  <attDef ident="rend" mode="delete"/>
                  <attDef ident="rendition" mode="delete"/>
                  <attDef ident="type" mode="delete"/>
                  <attDef ident="source" mode="delete"/>
                  <attDef ident="subtype" mode="delete"/>
                  <attDef ident="target" mode="change" usage="req"/>
               </attList>
            </elementSpec>
      </schemaSpec>
      </body>
  </text>
</TEI>
```
Run with this ANT code:

```
<target name="createRng">
  <echo message="${echo.separator}"/>
  <echo message="Now converting to RNG..."/>
  <echo message="Tei plugin located: ${teiPlugin}"/>
  <xslt force="yes" style="${teiPlugin}/xml/tei/stylesheet/odds/odd2odd.xsl" in="${odd.src}" out="${odd.processed}" classpath="../../editor_tools/tools/jars/saxon9he.jar">
   <factory name="net.sf.saxon.TransformerFactoryImpl">
    <attribute name="http://saxon.sf.net/feature/xinclude-aware" value="true"/>
   </factory>
   <param name="lang" expression="${lang}" if="lang"/>
   <param name="defaultSource" expression="${defaultSource}" if="defaultSource"/>
   <param name="selectedSchema" expression="${selectedSchema}" if="selectedSchema"/>
   <param name="verbose" expression="${verbose}" if="verbose"/>
  </xslt>
  <buildgeneric type="relaxng" xsl="${teiPlugin}/xml/tei/stylesheet/profiles/tei/relaxng/to.xsl" in="${odd.processed}" out="${schema}"/>
 </target> 
```

Produces this error: 
```
createRng:
     [echo] *************************************
     [echo] Now converting to RNG...
     [echo] Tei plugin located: /home/netlink/jtakeda/.com.oxygenxml/extensions/v19.0/frameworks/http___teijenkins.hcmc.uvic.ca_job_oxygen_tei_bleeding_lastSuccessfulBuild_artifact_oxygen_tei_updateSite.oxygen/tei
     [xslt] Processing /home/netlink/jtakeda/ise/ise3/svn/sch/test.odd to /home/netlink/jtakeda/ise/ise3/svn/sch/test-expanded-processed.odd
     [xslt] Loading stylesheet /home/netlink/jtakeda/.com.oxygenxml/extensions/v19.0/frameworks/http___teijenkins.hcmc.uvic.ca_job_oxygen_tei_bleeding_lastSuccessfulBuild_artifact_oxygen_tei_updateSite.oxygen/tei/xml/tei/stylesheet/odds/odd2odd.xsl
     [echo] XSLT generate relaxng files
     [xslt] Processing /home/netlink/jtakeda/ise/ise3/svn/sch/test-expanded-processed.odd to /home/netlink/jtakeda/ise/ise3/svn/sch/test.rng
     [xslt] Loading stylesheet /home/netlink/jtakeda/.com.oxygenxml/extensions/v19.0/frameworks/http___teijenkins.hcmc.uvic.ca_job_oxygen_tei_bleeding_lastSuccessfulBuild_artifact_oxygen_tei_updateSite.oxygen/tei/xml/tei/stylesheet/profiles/tei/relaxng/to.xsl
     [xslt] *** Internal problem: Base value for indexed filter is not indexable (net.sf.saxon.expr.LetExpression)
     [xslt]     Filter at line 155 of file:/home/netlink/jtakeda/.com.oxygenxml/extensions/v19.0/frameworks/http___teijenkins.hcmc.uvic.ca_job_oxygen_tei_bleeding_lastSuccessfulBuild_artifact_oxygen_tei_updateSite.oxygen/tei/xml/tei/stylesheet/odds/classatts.xsl
     [xslt] $Q{http://saxon.sf.net/generated-variable}loc847320212[(data(attribute::attribute(Q{}ident))) = $Q{http://saxon.sf.net/generated-variable}loc2145896000]
     [xslt] *** Internal problem: Base value for indexed filter is not indexable (net.sf.saxon.expr.LetExpression)
     [xslt]     Filter at line 155 of file:/home/netlink/jtakeda/.com.oxygenxml/extensions/v19.0/frameworks/http___teijenkins.hcmc.uvic.ca_job_oxygen_tei_bleeding_lastSuccessfulBuild_artifact_oxygen_tei_updateSite.oxygen/tei/xml/tei/stylesheet/odds/classatts.xsl
     [xslt] $Q{http://saxon.sf.net/generated-variable}loc847320212[(data(attribute::attribute(Q{}ident))) = $Q{http://saxon.sf.net/generated-variable}loc2145896000]
     [xslt] *** Internal problem: Base value for indexed filter is not indexable (net.sf.saxon.expr.LetExpression)
     [xslt]     Filter at line 155 of file:/home/netlink/jtakeda/.com.oxygenxml/extensions/v19.0/frameworks/http___teijenkins.hcmc.uvic.ca_job_oxygen_tei_bleeding_lastSuccessfulBuild_artifact_oxygen_tei_updateSite.oxygen/tei/xml/tei/stylesheet/odds/classatts.xsl
     [xslt] $Q{http://saxon.sf.net/generated-variable}loc847320212[(data(attribute::attribute(Q{}ident))) = $Q{http://saxon.sf.net/generated-variable}loc2145896000]
     [xslt] *** Internal problem: Base value for indexed filter is not indexable (net.sf.saxon.expr.LetExpression)
     [xslt]     Filter at line 155 of file:/home/netlink/jtakeda/.com.oxygenxml/extensions/v19.0/frameworks/http___teijenkins.hcmc.uvic.ca_job_oxygen_tei_bleeding_lastSuccessfulBuild_artifact_oxygen_tei_updateSite.oxygen/tei/xml/tei/stylesheet/odds/classatts.xsl
     [xslt] $Q{http://saxon.sf.net/generated-variable}loc847320212[(data(attribute::attribute(Q{}ident))) = $Q{http://saxon.sf.net/generated-variable}loc2145896000]
     [xslt] *** Internal problem: Base value for indexed filter is not indexable (net.sf.saxon.expr.LetExpression)
     [xslt]     Filter at line 155 of file:/home/netlink/jtakeda/.com.oxygenxml/extensions/v19.0/frameworks/http___teijenkins.hcmc.uvic.ca_job_oxygen_tei_bleeding_lastSuccessfulBuild_artifact_oxygen_tei_updateSite.oxygen/tei/xml/tei/stylesheet/odds/classatts.xsl
     [xslt] $Q{http://saxon.sf.net/generated-variable}loc847320212[(data(attribute::attribute(Q{}ident))) = $Q{http://saxon.sf.net/generated-variable}loc2145896000]
     [xslt] *** Internal problem: Base value for indexed filter is not indexable (net.sf.saxon.expr.LetExpression)
     [xslt]     Filter at line 155 of file:/home/netlink/jtakeda/.com.oxygenxml/extensions/v19.0/frameworks/http___teijenkins.hcmc.uvic.ca_job_oxygen_tei_bleeding_lastSuccessfulBuild_artifact_oxygen_tei_updateSite.oxygen/tei/xml/tei/stylesheet/odds/classatts.xsl
     [xslt] $Q{http://saxon.sf.net/generated-variable}loc847320212[(data(attribute::attribute(Q{}ident))) = $Q{http://saxon.sf.net/generated-variable}loc2145896000]
     [xslt] *** Internal problem: Base value for indexed filter is not indexable (net.sf.saxon.expr.LetExpression)
     [xslt]     Filter at line 155 of file:/home/netlink/jtakeda/.com.oxygenxml/extensions/v19.0/frameworks/http___teijenkins.hcmc.uvic.ca_job_oxygen_tei_bleeding_lastSuccessfulBuild_artifact_oxygen_tei_updateSite.oxygen/tei/xml/tei/stylesheet/odds/classatts.xsl
     [xslt] $Q{http://saxon.sf.net/generated-variable}loc847320212[(data(attribute::attribute(Q{}ident))) = $Q{http://saxon.sf.net/generated-variable}loc2145896000]
     [xslt] *** Internal problem: Base value for indexed filter is not indexable (net.sf.saxon.expr.LetExpression)
     [xslt]     Filter at line 155 of file:/home/netlink/jtakeda/.com.oxygenxml/extensions/v19.0/frameworks/http___teijenkins.hcmc.uvic.ca_job_oxygen_tei_bleeding_lastSuccessfulBuild_artifact_oxygen_tei_updateSite.oxygen/tei/xml/tei/stylesheet/odds/classatts.xsl
     [xslt] $Q{http://saxon.sf.net/generated-variable}loc847320212[(data(attribute::attribute(Q{}ident))) = $Q{http://saxon.sf.net/generated-variable}loc2145896000]
     [xslt] *** Internal problem: Base value for indexed filter is not indexable (net.sf.saxon.expr.LetExpression)
     [xslt]     Filter at line 155 of file:/home/netlink/jtakeda/.com.oxygenxml/extensions/v19.0/frameworks/http___teijenkins.hcmc.uvic.ca_job_oxygen_tei_bleeding_lastSuccessfulBuild_artifact_oxygen_tei_updateSite.oxygen/tei/xml/tei/stylesheet/odds/classatts.xsl
     [xslt] $Q{http://saxon.sf.net/generated-variable}loc847320212[(data(attribute::attribute(Q{}ident))) = $Q{http://saxon.sf.net/generated-variable}loc2145896000]
     [xslt] *** Internal problem: Base value for indexed filter is not indexable (net.sf.saxon.expr.LetExpression)
     [xslt]     Filter at line 155 of file:/home/netlink/jtakeda/.com.oxygenxml/extensions/v19.0/frameworks/http___teijenkins.hcmc.uvic.ca_job_oxygen_tei_bleeding_lastSuccessfulBuild_artifact_oxygen_tei_updateSite.oxygen/tei/xml/tei/stylesheet/odds/classatts.xsl
     [xslt] $Q{http://saxon.sf.net/generated-variable}loc847320212[(data(attribute::attribute(Q{}ident))) = $Q{http://saxon.sf.net/generated-variable}loc2145896000]
     [xslt] *** Internal problem: Base value for indexed filter is not indexable (net.sf.saxon.expr.LetExpression)
     [xslt]     Filter at line 155 of file:/home/netlink/jtakeda/.com.oxygenxml/extensions/v19.0/frameworks/http___teijenkins.hcmc.uvic.ca_job_oxygen_tei_bleeding_lastSuccessfulBuild_artifact_oxygen_tei_updateSite.oxygen/tei/xml/tei/stylesheet/odds/classatts.xsl
     [xslt] $Q{http://saxon.sf.net/generated-variable}loc847320212[(data(attribute::attribute(Q{}ident))) = $Q{http://saxon.sf.net/generated-variable}loc2145896000]
     [xslt] *** Internal problem: Base value for indexed filter is not indexable (net.sf.saxon.expr.LetExpression)
     [xslt]     Filter at line 155 of file:/home/netlink/jtakeda/.com.oxygenxml/extensions/v19.0/frameworks/http___teijenkins.hcmc.uvic.ca_job_oxygen_tei_bleeding_lastSuccessfulBuild_artifact_oxygen_tei_updateSite.oxygen/tei/xml/tei/stylesheet/odds/classatts.xsl
     [xslt] $Q{http://saxon.sf.net/generated-variable}loc847320212[(data(attribute::attribute(Q{}ident))) = $Q{http://saxon.sf.net/generated-variable}loc2145896000]
     [xslt] *** Internal problem: Base value for indexed filter is not indexable (net.sf.saxon.expr.LetExpression)
     [xslt]     Filter at line 155 of file:/home/netlink/jtakeda/.com.oxygenxml/extensions/v19.0/frameworks/http___teijenkins.hcmc.uvic.ca_job_oxygen_tei_bleeding_lastSuccessfulBuild_artifact_oxygen_tei_updateSite.oxygen/tei/xml/tei/stylesheet/odds/classatts.xsl
     [xslt] $Q{http://saxon.sf.net/generated-variable}loc847320212[(data(attribute::attribute(Q{}ident))) = $Q{http://saxon.sf.net/generated-variable}loc2145896000]
     [xslt] *** Internal problem: Base value for indexed filter is not indexable (net.sf.saxon.expr.LetExpression)
     [xslt]     Filter at line 155 of file:/home/netlink/jtakeda/.com.oxygenxml/extensions/v19.0/frameworks/http___teijenkins.hcmc.uvic.ca_job_oxygen_tei_bleeding_lastSuccessfulBuild_artifact_oxygen_tei_updateSite.oxygen/tei/xml/tei/stylesheet/odds/classatts.xsl
     [xslt] $Q{http://saxon.sf.net/generated-variable}loc847320212[(data(attribute::attribute(Q{}ident))) = $Q{http://saxon.sf.net/generated-variable}loc2145896000]
     [xslt] *** Internal problem: Base value for indexed filter is not indexable (net.sf.saxon.expr.LetExpression)
     [xslt]     Filter at line 155 of file:/home/netlink/jtakeda/.com.oxygenxml/extensions/v19.0/frameworks/http___teijenkins.hcmc.uvic.ca_job_oxygen_tei_bleeding_lastSuccessfulBuild_artifact_oxygen_tei_updateSite.oxygen/tei/xml/tei/stylesheet/odds/classatts.xsl
     [xslt] $Q{http://saxon.sf.net/generated-variable}loc847320212[(data(attribute::attribute(Q{}ident))) = $Q{http://saxon.sf.net/generated-variable}loc2145896000]
     [xslt] *** Internal problem: Base value for indexed filter is not indexable (net.sf.saxon.expr.LetExpression)
     [xslt]     Filter at line 155 of file:/home/netlink/jtakeda/.com.oxygenxml/extensions/v19.0/frameworks/http___teijenkins.hcmc.uvic.ca_job_oxygen_tei_bleeding_lastSuccessfulBuild_artifact_oxygen_tei_updateSite.oxygen/tei/xml/tei/stylesheet/odds/classatts.xsl
     [xslt] $Q{http://saxon.sf.net/generated-variable}loc847320212[(data(attribute::attribute(Q{}ident))) = $Q{http://saxon.sf.net/generated-variable}loc2145896000]
     [xslt] *** Internal problem: Base value for indexed filter is not indexable (net.sf.saxon.expr.LetExpression)
     [xslt]     Filter at line 155 of file:/home/netlink/jtakeda/.com.oxygenxml/extensions/v19.0/frameworks/http___teijenkins.hcmc.uvic.ca_job_oxygen_tei_bleeding_lastSuccessfulBuild_artifact_oxygen_tei_updateSite.oxygen/tei/xml/tei/stylesheet/odds/classatts.xsl
     [xslt] $Q{http://saxon.sf.net/generated-variable}loc847320212[(data(attribute::attribute(Q{}ident))) = $Q{http://saxon.sf.net/generated-variable}loc2145896000]
[...snip...]
```

**Comment by sydb** [comment] 2017-07-22 00:49
I have oXygen 19.0 build 2017033118 on my (GNU/Linux) desktop. It uses Saxon 9.7.0.15. I’ve confirmed @joeytakeda’s bug happens to me, too. (I’m using the standard 3.1.0 and 7.42.0 frameworks.)

However, I generated RELAX NG from the same ODD without problem using commandline `roma` and `teitorelaxng`, each of which uses my local copy of Saxon HE, which is version 9.7.0.3J. I then updated to 9.8.0.3J, and both still worked (although I got a “The parent axis starting at a document node will never select anything” warning with `roma`).

So I’m thinking this is a solved Saxon problem, not a TEI problem. Thus the solution for oXygen to update to the newest version of Saxon. Once someone agrees with me I’ll send it along to SyncRO Soft.

**Comment by martindholmes** [comment] 2017-08-09 17:55
This might be a bug arising out of Oxygen's use of special optimizations when it calls saxon9ee, which we've seen before:

https://github.com/TEIC/Stylesheets/issues/234
https://github.com/TEIC/oxygen-tei/issues/15
https://github.com/TEIC/Stylesheets/issues/233

The odd-to-relax transformation uses saxon9ee explicitly. I believe this can be prevented by replacing it with saxon9he, and/or commenting out the oxygen.jar file. I'm going to test that and see if the problem is solved with a test file. I'll make the change, let the bleeding-edge plugin build itself, then see if the test ODD works in Oxygen.

**Comment by martindholmes** [comment] 2017-08-09 18:20
Converting the test file with the bleeding-edge version of the plugin, updated today, with Oxygen 19.0 2017-04-20and TEI Version 3.3.0a last updated on,	7th August 2017, revision 33e8a19, the RNG file is produced with no problem. I'm going to get the latest Oxy build and test again to see if it's a regression.

**Comment by martindholmes** [comment] 2017-08-09 18:27
No problem with Oxy build 2017062918. @joeytakeda and @sydb can you confirm that if you call the TEI ODD to RelaxNG (XML syntax) built-in transformation on the test file in Oxygen, you still see the error?

**Comment by joeytakeda** [comment] 2017-10-21 22:01
Sorry for the lateness of the reply! I'm using the same Oxy build (2017062918) and TEI Version 3.3.25, build number 2017-10-13-103823 and I am still seeing the almost exactly the same error; the only difference, as far as I can tell, is that the line number has changed from line 155 to 153. 

```
 Loading stylesheet /Users/joeytakeda/Library/Preferences/com.oxygenxml/extensions/v19.0/frameworks/http___teijenkins.hcmc.uvic.ca_job_oxygen_tei_bleeding_lastSuccessfulBuild_artifact_oxygen_tei_updateSite.oxygen/tei/xml/tei/stylesheet/profiles/tei/relaxng/to.xsl
     [xslt] *** Internal problem: Base value for indexed filter is not indexable (net.sf.saxon.expr.LetExpression)
     [xslt]     Filter at line 153 of file:/Users/joeytakeda/Library/Preferences/com.oxygenxml/extensions/v19.0/frameworks/http___teijenkins.hcmc.uvic.ca_job_oxygen_tei_bleeding_lastSuccessfulBuild_artifact_oxygen_tei_updateSite.oxygen/tei/xml/tei/stylesheet/odds/classatts.xsl
     [xslt] $Q{http://saxon.sf.net/generated-variable}loc192428201[(data(attribute::attribute(Q{}ident))) = $Q{http://saxon.sf.net/generated-variable}loc1894758168]
     [xslt] *** Internal problem: Base value for indexed filter is not indexable (net.sf.saxon.expr.LetExpression)
     [xslt]     Filter at line 153 of file:/Users/joeytakeda/Library/Preferences/com.oxygenxml/extensions/v19.0/frameworks/http___teijenkins.hcmc.uvic.ca_job_oxygen_tei_bleeding_lastSuccessfulBuild_artifact_oxygen_tei_updateSite.oxygen/tei/xml/tei/stylesheet/odds/classatts.xsl
     [xslt] $Q{http://saxon.sf.net/generated-variable}loc192428201[(data(attribute::attribute(Q{}ident))) = $Q{http://saxon.sf.net/generated-variable}loc1894758168]
     [xslt] *** Internal problem: Base value for indexed filter is not indexable (net.sf.saxon.expr.LetExpression)
     [xslt]     Filter at line 153 of file:/Users/joeytakeda/Library/Preferences/com.oxygenxml/extensions/v19.0/frameworks/http___teijenkins.hcmc.uvic.ca_job_oxygen_tei_bleeding_lastSuccessfulBuild_artifact_oxygen_tei_updateSite.oxygen/tei/xml/tei/stylesheet/odds/classatts.xsl
     [xslt] $Q{http://saxon.sf.net/generated-variable}loc192428201[(data(attribute::attribute(Q{}ident))) = $Q{http://saxon.sf.net/generated-variable}loc1894758168]
     [xslt] *** Internal problem: Base value for indexed filter is not indexable (net.sf.saxon.expr.LetExpression)
     [xslt]     Filter at line 153 of file:/Users/joeytakeda/Library/Preferences/com.oxygenxml/extensions/v19.0/frameworks/http___teijenkins.hcmc.uvic.ca_job_oxygen_tei_bleeding_lastSuccessfulBuild_artifact_oxygen_tei_updateSite.oxygen/tei/xml/tei/stylesheet/odds/classatts.xsl
     [xslt] $Q{http://saxon.sf.net/generated-variable}loc192428201[(data(attribute::attribute(Q{}ident))) = $Q{http://saxon.sf.net/generated-variable}loc1894758168]
     [xslt] *** Internal problem: Base value for indexed filter is not indexable (net.sf.saxon.expr.LetExpression)
     [xslt]     Filter at line 153 of file:/Users/joeytakeda/Library/Preferences/com.oxygenxml/extensions/v19.0/frameworks/http___teijenkins.hcmc.uvic.ca_job_oxygen_tei_bleeding_lastSuccessfulBuild_artifact_oxygen_tei_updateSite.oxygen/tei/xml/tei/stylesheet/odds/classatts.xsl
     [xslt] $Q{http://saxon.sf.net/generated-variable}loc192428201[(data(attribute::attribute(Q{}ident))) = $Q{http://saxon.sf.net/generated-variable}loc1894758168]
[...etc..]
```

**Comment by sydb** [comment] 2018-01-12 18:31
I just tesetd in XML Developer 19.1, build 2017092911, and had no problems.

**Comment by martindholmes** [comment] 2018-01-12 18:31
@joeytakeda Can you update your Oxygen to the latest version and see if you can reproduce it? We can't make it happen on Mac or Linux with the current Oxygen.

**Comment by joeytakeda** [comment] 2018-01-12 19:27
Updated to Oxygen 19.1 build 2017121318 and no more error! Thanks

**Comment by martindholmes** [comment] 2018-01-12 20:36
Closing this, then. There should be a category "Not fixed; went away."

**Closed by martindholmes** 2018-01-12 20:36 UTC
