### ISSUE TITLE
empty attList after ODD compilation

### ISSUE THREAD

**Issue by bansp** [TEIC/Stylesheets#210] opened 2016-12-31 17:12 UTC
I have noticed that my augmented ODD (derived with `teitoodd`) does not validate because of empty `<attList>` elements. An example (shortened) declaration follows:
```xml
<elementSpec rend="change" module="nets" ident="forest">
          <gloss versionDate="2007-06-12" xml:lang="fr">forêt</gloss>
          <desc versionDate="2005-01-14" xml:lang="en">provides for groups of rooted trees.</desc>
          <classes>
            <memberOf key="model.annotation"/> <!-- this may be relevant -->
            <memberOf key="att.global"/>
            <memberOf key="att.typed"/>
            <memberOf key="model.divPart"/>
          </classes>
          <content>
            <alternate minOccurs="1" maxOccurs="unbounded">
              <elementRef key="tree"/>
              <elementRef key="eTree"/>
              <elementRef key="triangle"/>
            </alternate>
          </content>
          <attList/>  <!-- this is the offending bit -->

          <!--<exemplum xml:lang="und">... </exemplum> <remarks>...</remarks>-->
          <listRef>
            <ref target="http://www.tei-c.org/release/doc/tei-p5-doc/en/html/GD.html#GDAT">19.3. Another Tree Notation</ref>
          </listRef>
        </elementSpec>
```
On first glance, most of these occur if an element is declared as a memberOf "model.annotation", declared in Peter and Laurent's [standOff spec](https://github.com/laurentromary/stdfSpec/blob/AnnArbor/Specification/standoff-proposal.xml), the relevant declaration being as follows:
```xml
<classSpec type="model" ident="model.annotation" mode="add" module="standOff">
       <desc>groups together any kind of element that may be used to annotate an 
                  annotable segment</desc>
</classSpec>
```
(At this point, I am beginning to realise that this need not be a tool issue at all, but please kindly bear with me...)
The question now is: what gives? Is this some issue with the definition of the classSpec for the module that is responsible for this (but: "[In the case of model classes, no further information is needed to define the class beyond its description, its identifier, and optionally any classes of which it is a member.](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/TD.html#TDCLA)"), or is this a more general issue that could be rooted in some potential recent changes to the tool or to the Guidelines?
Thanks in advance!

**Comment by lb42** [comment] 2016-12-31 17:18
If you refer to the spec for attList you will see that it must have at least one child element.

**Comment by bansp** [comment] 2016-12-31 17:19
Hi Lou, no I don't think I refer to a spec for attList :-)

**Comment by lb42** [comment] 2016-12-31 17:20
Let's try again. Why are you putting an attList on your odd?

**Comment by bansp** [comment] 2016-12-31 17:22
The listing above is a nearly random declaration after ODD augmentation against the p5subset currently distributed in the TEI framework for oXygen. It comes from an ODD slightly modified from the version by Peter and Laurent (https://github.com/laurentromary/stdfSpec/blob/AnnArbor/Specification/standoff-proposal.xml). I am not putting an attList anywhere, it gets there via ODD augmentation.

**Comment by bansp** [comment] 2016-12-31 17:24
I have also noticed this problem (among a few others) in Laurent's augmented ODD in the standOff repository.

**Comment by lb42** [comment] 2016-12-31 17:46
I am not entirely sure what you mean by odd augmentation. But if the end product is supposed to be a tei conformant document, I am here to tell you that an empty attList is not permitted by the tei schema.

**Comment by bansp** [comment] 2016-12-31 18:00
The lawless `<attList>` is exactly why I asked. It was introduced into the schema after I processed an ODD with `teitoodd`. Since it shouldn't be in a valid schema, I was concerned that maybe `teitoodd` does something that it shouldn't do.

I thought I knew the term "ODD augmentation" from you, but maybe I was just being clever and thought it up myself (nahh). I mean ODD processed against (e.g.) a p5subset, containing all the definitions and so on. "Processed ODD"? Nevermind the naming, I got it by processing an ODD document with `teitoodd`, which is what prompted me to post the issue here; I counted on the potential familiarity with this sort of problems on the part of Stylesheets developers. I was hoping to find it listed among the existing issues but failed to.

**Comment by lb42** [comment] 2016-12-31 18:04
Ok, that does sound like a bug. Can you send me the odd file which you processed with teitoodd so can investigate further. Though probably not tonight....

**Comment by martindholmes** [comment] 2016-12-31 18:29
We have just had a bit of a process to define nomenclature for the various odd-processing steps; the results are here:

http://wiki.tei-c.org/index.php/Mapping_ODD_processing

We decided on compile/compilation as the term for munging together an ODD with p5subset.xml to create an expanded/processed/compiled ODD.

**Comment by martindholmes** [comment] 2016-12-31 18:31
One question though: normally the compiled ODD is only a stage in the generation of a schema or documentation, and is discarded afterwards. Is it a problem if it's not strictly valid?

**Comment by bansp** [comment] 2016-12-31 18:32
It looks like I will indeed have to send it by mail, gitHub won't accept a .zip from me.
And thanks @martin for the link! Will investigate that tomorrow.

**Comment by bansp** [comment] 2016-12-31 18:35
Hi Lou,
Trying this way.
Thanks and all the best for the new year! :-)
   Piotr

**Comment by martindholmes** [comment] 2016-12-31 19:19
I've encountered this problem with attaching zips several times; GitHub says you can do it:

https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/

but it doesn't work. I'll look into it.

**Comment by hcayless** [comment] 2016-12-31 19:21
I actually thought I'd fixed this one. But obviously either I didn't or we've had a regression. It didn't really matter when compiled ODDs were just a step in the schema generation process, but with chaining, they'll sometimes need to be published artifacts in their own right.

**Comment by martindholmes** [comment] 2016-12-31 19:24
Testing uploading a zipped ODD file...
[tei_all.odd.zip](https://github.com/TEIC/Stylesheets/files/679782/tei_all.odd.zip)

**Comment by martindholmes** [comment] 2016-12-31 19:45
Piotr, are you using the current dev branch of the Stylesheets, or an old release?

**Comment by bansp** [comment] 2016-12-31 21:20
Hi Martin, 
The currentest ;-) branch possible, unless you guys make a difference between master and development. I cloned and called make, basically (modulo ant-related tweaks).
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by bansp** [comment] 2017-01-01 16:49
PS. I've just tried it without specifying the local source, so it took the freshest p5subset from the Vault, and while some of the resulting differences are pretty dramatic (so I won't be using the version from the TEI Framework and I'm all the more grateful for this discussion), the empty `<attList/>` is still there, in the compiled ODD.

**Comment by bansp** [comment] 2017-01-01 16:53
[standoff-ODD.xml.zip](https://github.com/TEIC/Stylesheets/files/680089/standoff-ODD.xml.zip)
Ah, so cool, it's my 5th attempt today, and now the .zip attachment appears to work. 

This file is taken from [Laurent's standoff repository](https://github.com/laurentromary/stdfSpec) and very slightly modified to make it valid with my local tei_odds (so please mind the PIs at the top). I would like to use the compiled ODD for chaining, so I opened it, noticed the validation problems, and thought I would ask about them here.

**Comment by lb42** [comment] 2017-01-01 18:20
I can confirm that this is a bug in the stylesheets. A change in the class membership of a model class should not generate an empty attList in the model class spec. Indeed, an attList is not really valid within a model class spec anyway.  

There also seems to be a related bug when a modification removes all the attributes from an attribute class. Presumably because this might cause problems if some other class references this class, the stylesheet does not remove the class spec itself ; instead the class spec is kept,  but with an empty attribute list, which (as aforesaid) is syntactically invalid.  (see e.g. tei_bare for an example of this)

**Comment by lb42** [comment] 2017-01-01 18:52
Another weird problem in the output from the same stylesheet, applied to almost any ODD: the datatype declarations it produces in e.g.  the form 
~~~~
<datatype><dataRef key="teidata.numeric"/></datatype>
~~~~
 are invalid according to the tei_odds schema. The error message reads "datatype content must be in the namespace '' " err?

**Comment by martindholmes** [comment] 2017-01-01 19:17
There's a Schematron rule in Schema/tei.rng which is expecting datatypes to be in the RelaxNG namespace:

~~~~~
<pattern xmlns="http://purl.oclc.org/dsdl/schematron" id="d8e119324-constraint">
         <rule context="tei:datatype">
            <report test="descendant::*[not(namespace-uri(.) = ('http://relaxng.org/ns/structure/1.0'))]">datatype content must be in the namespace ''</report>
         </rule>
      </pattern>
~~~~~

**Comment by martindholmes** [comment] 2017-01-01 19:23
And that seems to be an erroneous output from Source/Specs/datatype.xml:

~~~~~
  <content>
    <alternate>
      <elementRef key="textNode"/>
      <elementRef key="dataRef"/>
      <anyElement require="http://relaxng.org/ns/structure/1.0"/>
    </alternate>
  </content>
~~~~~

The requirement for anyElement to be in the RelaxNG namespace seems to be applied equally to the elements in the TEI namespace.

**Comment by martindholmes** [comment] 2017-01-01 19:28
The Stylesheets code problem comes at line 424 of Stylesheets/odds/odd2relax.xsl.

**Comment by bansp** [comment] 2017-01-02 12:54
I have successfully chained from this ill-formed ODD (by reducing the element repertoire) and, oddly enough, the resulting schema behaves very well: in the XML instance based on that schema, `<seg>` (which in the compiled ODD gets the empty `<attList/>`) accepts the regular attributes, `@who` allows for multiple URI values, and `@ref` requires at least one value.

In the compiled ODD, the following bits cause validation errors:
who: `<datatype maxOccurs="unbounded"><dataRef key="teidata.pointer"/></datatype>`
ref: `<datatype minOccurs="1" maxOccurs="unbounded"><dataRef key="teidata.pointer"/></datatype>`

HTH, somehow...

**Comment by lb42** [comment] 2017-01-02 13:34
These are all related issues, apparently derived from a bug in the way the new &lt;anyElement> element is processed by the stylesheets. Thanks to @martindholmes for tracking down the details. Waiting for @hcayless to check the code, since it's his!

**Comment by bansp** [comment] 2017-01-02 14:50
What I'm saying is that the issues were hiding really well, because the symptoms are not there (resulting schemas are as expected, at least a quick check would suggest so).

**Comment by hcayless** [comment] 2017-01-02 22:49
Just tried out fixing the attList thing, and it's a lot more complicated than it might appear, so I reverted the change. We never try to validate compiled ODDs, so the empty attLists don't cause any issues. I'm looking at the  other issues.

**Comment by lb42** [comment] 2017-01-02 22:53
I agree that the other issues are more worrying, since they actually break almost any ODD, but I don't agree that empty attLists "don't cause any issues". We recommend people to create and use compiled ODDs, which are supposed to be TEI documents, so they really ought to be valid!

**Comment by martindholmes** [comment] 2017-01-02 23:34
Where do we recommend that people use compiled ODDs? They're normally deleted automatically after a schema or documentation is created.

Not that I don't think they should be valid, of course.

**Comment by lb42** [comment] 2017-01-02 23:52
In my tutorial on odd chaining. An odd must be compiled to chain it.

**Comment by bansp** [comment] 2017-01-03 00:19
Would it be an acceptable compromise for the time being to have the executable, `teitoodd`, perform a second pass over the compiled ODD, removing stray empty attLists? It's admittedly a kludge vis-a-vis a clean solution whereby a single script would do all, but as a result, there would be a way to derive a clean compiled ODD, and it would be in a way a 'clean kludge', in the sense that it'd clearly show what remains to be done.

**Comment by martindholmes** [comment] 2017-01-03 00:46
I'm not keen on that because it makes the problem go away so we'll forget about it, but it does so through the sort of magic that will come back and bite us later, or at the very least, mystify people trying to figure out how the Stylesheets work some time in the future.

**Comment by bansp** [comment] 2017-01-04 02:18
This is a good argument against kludges in general, but all I wanted to say is that:
(i) there are kludges which require you to locate them and decipher them and often scream more than once, but this would be "clean" in the sense that it's almost like a "to-do": it precisely identifies the issue and is located in a single chunk of code. 
(ii) you guys might be under time pressure (that's an easy guess) and this is not a release-stopper; however, it might be better to have at least one way to compile a fully valid ODD now that more and more people get interested in chaining ODDs, so that they're energy can be allocated to further development and giving feedback rather than rediscovering stray attLists in compiled ODDs. Maybe even one of those people will decide to help getting rid of the kludge if it's clearly commented and practically on the plate.
That's why I called it a compromise. Not an optimal solution but not the dirtiest either. Just wanted to run it by you in case you'd feel torn between other commitments and an urge to do something about this bug. Cheers :-)

**Comment by martindholmes** [comment] 2017-01-04 06:41
I'm particularly nervous about kludges at the moment because I've been doing a lot of work in the Stylesheets, partly to help me figure out what they're actually doing. I keep on discovering lurking hacks like this. It takes a remarkable amount of time to figure out why they're their and what they're hiding, mainly because they were done quickly because of time pressure and therefore not documented properly. I think we need to get more rigorous and methodical about this stuff, otherwise we'll never be able to develop and maintain the codebase over the long term.

**Comment by bansp** [comment] 2017-03-11 13:36
Martin, I accept a "no" from a person who is deeply involved into this, by all means. I just want to stress that the kludge I was proposing would not be lurking or hiding. I would call it a "patch" rather than a "kludge", if the former term hadn't been taken :-) 
I'm not trying to convince you now, just pointing out the difference, for the record :-)

**Comment by martindholmes** [comment] 2017-03-11 14:40
There are other open tickets that might also be addressed by a final pass over the processed odd, so perhaps this is really an effective strategy for the moment.

**Comment by martindholmes** [comment] 2020-10-30 15:35
@bansp Can you check your original ticket submission? @sydb just noticed that you have `@rend="change"` instead of `@mode="change`".

**Comment by bwbohl** [comment] 2024-05-27 07:08
shouldn’t this be fixed with https://github.com/TEIC/Stylesheets/commit/a855bbe57efabe0881f283487970b3892910a0f0?

**Comment by sydb** [comment] 2024-05-27 20:53
Sure looks that way to me. And my quick scan says (unlike #319) there are no other bugs reported on this issue. So closing as completed (with thanks to @bwbohl both for noticing this should-have-been-closed issue and for the PR that fixed it).

**Closed by sydb** 2024-05-27 20:53 UTC
Labels: type: bug, resp: council, status: needsDiscussion, conversion: odd, status: confirmed
