### ISSUE TITLE
White space not preserved in docx-to-tei transform

### ISSUE THREAD

**Issue by Conal-Tuohy** [TEIC/Stylesheets#64] opened 2014-11-13 07:26 UTC
Specifically my problem lies here: https://github.com/TEIC/Stylesheets/blob/master/docx/from/textruns.xsl#L405

The first case handles a text run which is purely white space, with `xml:space="preserve"` by substituting a single space. That doesn't match the semantics of `xml:space="preserve"` at all.

In the second case, where a text run includes at least one non-whitespace character, the white space is preserved, but because `xml:space="preserve"` is not propagated into the TEI, this white space is liable to be stripped by a downstream processor.

I actually don't quite understand the logic here; perhaps this is just a simple bug but perhaps I'm missing something, and this is intentional.

But my own thinking is that white space in a docx document *is* significant, and *should* in general be preserved; white space should not be discarded, and should be marked with `xml:space="preserve"` in the TEI (unless there is no actual space to preserve).

I have made an experimental change like so, which implements the above. 

```xml
<!--
 <xsl:when test="@xml:space='preserve' and string-length(normalize-space(.))=0">
	  <seg><xsl:text> </xsl:text></seg>
 </xsl:when>
 <xsl:when test="@xml:space='preserve'">
	  <xsl:value-of select="."/>
 </xsl:when>
 -->
<!-- preserve significant white space which might otherwise be lost -->
<xsl:when test="@xml:space='preserve' and normalize-space(.) != string(.)"
><seg xml:space="preserve"><xsl:value-of select="."/></seg></xsl:when>

```

I'm not entirely happy with it though, because it is overly cautious about preserving spaces. Sometimes a `seg[@xml:space='preserve']` will be generated only because a text run ends with a space character, even though it may be followed in the TEI output by another text node which would have had the effect of preventing trimming of that trailing white space anyway. I'm not sure how best to do deal with that case; perhaps by post-processing?

**Comment by sebastianrahtz** [comment] 2015-05-04 18:54
returning to this after some more changes.

can we just remove the first when, so that the code reads

`               <xsl:when test="@xml:space='preserve'">
                    <xsl:value-of select="."/>
                </xsl:when>
                <xsl:otherwise>
                    <xsl:value-of select="normalize-space(.)"/>
                </xsl:otherwise>`

and then trust other code not to strip out the space?

**Comment by Conal-Tuohy** [comment] 2015-05-04 21:59
The issue, to me, is that the significance of WS in TEI is not generally defined,  absent xml:whitespace attributes. Much of the whitespace in an ex-Word TEI doc is insignificant (e.g. between paras) but whitespace inside of text runs is always (?) significant. If that WS ends up in the TEI in a text node for which not (.=normalize-space (.)) then it needs to be marked for preservation.

**Comment by sebastianrahtz** [comment] 2015-05-05 21:38
whitespace inside runs is significant, yes. But we combine together all the w:t inside a w:r to make one object in the TEI, so the whitespace only matters at start and finish. the problem is trying to isolate that situation

**Comment by Conal-Tuohy** [comment] 2015-05-06 21:21
'at start and finish'?

**Comment by sebastianrahtz** [comment] 2015-05-07 18:38
I am closing this issue, because its the same conversation as 106, and I can't see how to merge them.

**Closed by sebastianrahtz** 2015-05-07 18:38 UTC
