### ISSUE TITLE
Links from element names to their Spec pages in the PDF are broken

### ISSUE THREAD

**Issue by martindholmes** [TEIC/Stylesheets#360] opened 2019-02-15 22:05 UTC
In the current release of the Guidelines PDF, element names are linked, but instead of linking to their individual spec pages, they all link to the same place: the beginning of Appendix C1.

**Comment by jamescummings** [comment] 2019-02-15 22:07
Confirm that this is the case. 

To reproduce, see https://www.tei-c.org/release/doc/tei-p5-doc/en/Guidelines.pdf, find an element name and click on it. You go to the correct appendix but not the element itself. (Something to do with IDs in creating the LaTeX?)

**Comment by peterstadler** [comment] 2019-02-17 20:37
I checked the code base and couldn't find any recent changes that might be responsible for the issue at hand. (The PDF is the result of the chain ODD->Lite->LaTeX->PDF and the Lite output features the needed `@xml:id`s, and the tex-file looks good as well)

Hence, I believe the TeX-processing has changed somehow?  Somehow the `reflist` (the LaTeX wrapper for every spec) is not seen as a sectionlike thing anymore?

My proposed fix in 75f132364a253e68825b1692884045e58ab6c3d9 simply adds a `phantomsection` (see https://en.wikibooks.org/wiki/LaTeX/Labels_and_Cross-referencing#Anchor_manual_positioning) before the label to point directly to the line where the `\label` is defined.

While that works (for me in a local build) I will need a bit more testing and research whether other links are affected as well.

**Comment by peterstadler** [comment] 2019-05-08 20:33
Just checked the proposed fix:
* cross references to attributes, elements, datatypes, macros do work
* cross references to bibliographic items *do not* work. See e.g. references in footnote 5

**Comment by martindholmes** [comment] 2019-07-05 21:18
This all looks fine to me, but I know nothing about LaTeX, so my opinion is pretty worthless. If it fixes the problem, though, go for it!

**Comment by peterstadler** [comment] 2019-07-05 21:23
Thanks @martindholmes! Have you been able to build the PDF on your machine (and check those links)?

**Comment by martindholmes** [comment] 2019-07-05 21:38
I don't have all the xelatex stuff installed on my machine. I'll have to get all that working first, then I'll try.

**Comment by martindholmes** [comment] 2019-07-05 21:55
Building with the peterstadler-issue360 version of the Stylesheets, I see that many links do work, but links from chapter prose (using `<gi>`) to appendix spec pages don't work; they still seem to point to the appendix as before. For example, go to p. 40 and click on the first instance of `<projectDesc>'. My build process does end with an error, with no helpful information, but the PDF is created. I don't know how helpful this is. But if it builds correctly for you and these links work, then I would commit and see what Jenkins makes of it. Setting up LaTeX stuff is gnarly and I may not have it right.

**Comment by peterstadler** [comment] 2019-07-10 22:19
just checked again with my local build (and found a tiny cosmetic flaw I fixed in a83ee2de5ad47fbfe11073a8fdf32d54abada97a) 

That said, I can't reproduce @martindholmes' issue on p. 40 but do get a nice output. Please have a look at the PDF at https://uni-paderborn.sciebo.de/s/dlglQarJd52xRLN which I built locally.

**Comment by martindholmes** [comment] 2019-07-10 22:43
Your locally-built one is indeed fine, so I would push to dev and see what Jenkins does.

**Comment by peterstadler** [comment] 2019-07-11 05:39
Thanks again @martindholmes for checking! Would you mind to hit the "merge" button yourself since @jamescummings is probably distracted by DH@Utrecht?

**Comment by peterstadler** [comment] 2019-07-12 06:41
PR merged, checked the [PDF on Jenkins](https://jenkins-paderborn.tei-c.org/job/TEIP5-dev/277/artifact/P5/release/doc/tei-p5-doc/en/Guidelines.pdf), all seems fine, closing :)

**Closed by peterstadler** 2019-07-12 06:41 UTC
Labels: CouncilResponsibility, Release Blocker, bug
