### ISSUE TITLE
Stylesheets build tests failing

### ISSUE THREAD

**Issue by martindholmes** [TEIC/Stylesheets#147] opened 2016-04-07 12:43 UTC
I'm raising an issue for this because I don't really understand why it was suddenly triggered following the release of 7.41.0, where everything was working perfectly.

The build process falls over on an early test, which generates test.rng and diffs it with expected-results/test.rng. These two files are wildly different, so something in the build process generates a completely different result from what was happening before. Most of the differences seem to relate to datatypes. Here's a single example:

Newly-generated:

```
  <define name="att.cReferencing.attribute.cRef">
    <optional>
      <attribute name="cRef">
        <a:documentation xmlns:a="http://relaxng.org/ns/compatibility/annotations/1.0">(canonical reference) specifies the destination of the pointer by supplying a canonical reference expressed using the scheme defined in a refsDecl element in the TEI header</a:documentation>
        <data type="string"/>
      </attribute>
    </optional>
  </define>
```

Expected:

```
  <define name="att.cReferencing.attribute.cRef">
    <optional>
      <attribute name="cRef">
        <a:documentation xmlns:a="http://relaxng.org/ns/compatibility/annotations/1.0">(canonical reference) specifies the destination of the pointer by supplying a canonical reference expressed using the scheme defined in a refsDecl element in the TEI header</a:documentation>
        <ref name="data.text"/>
      </attribute>
    </optional>
  </define>
```

The key difference being:

```
<data type="string"/>
versus
<ref name="data.text"/>
```

Somebody who has a clearer understanding of what schemas generated from PureODD ODDs should look like will probably see the issue here immediately, but until it's fixed, we don't have a working Stylesheets build. If it's just a question of regenerating all the expected results files, that's trivial, but I'd like to understand what's happening before doing that.

**Comment by hcayless** [comment] 2016-04-07 13:00
I think this is because the default behavior of conversions that deal with ODDs is to go fetch the p5subset file from the last release. Some tests use a local copy but not all of them. The file has obviously changed a good deal in 3.0.0, so the test expected results need to be regenerated.

**Comment by martindholmes** [comment] 2016-04-07 15:47
Ah, curses. That's a circular dependency, then, because P5 depends on the Stylesheets. Can you think of a way around that? On Jenkins, the Stylesheets could pull from the P5 products from the same branch, but then in order to know if things are working properly or not, you'd have to do a complete cycle: build Stylesheets, build P5, build Stylesheets again to make sure that the P5 build didn't break anything, then build P5 again to make sure changes to the Stylesheets resulting from the rebuild of p5subset.xml didn't break anything. That's a bit loopy, in both senses.

**Comment by hcayless** [comment] 2016-04-07 15:54
Yep. Loopy indeed. We could just put a p5subset.xml in the Stylesheets as a test fixture. We'd have to remember to update it from time to time.

**Comment by martindholmes** [comment] 2016-04-07 16:19
The whole expected-results approach is a bit gnarly; if you make a major change, then you have to regenerate all of them and it's unlikely you'd actually look to confirm that every single difference is what you expected it to be. But I can't think of a good alternative. It would be nice to have a script that just says "regenerate all expected-results", but the temptation to use that whenever anything breaks would be significant.

**Comment by hcayless** [comment] 2016-04-15 20:48
The Stylesheets are building again, but I'm going to leave this open, because the problem is nowhere near solved yet.

**Comment by hcayless** [comment] 2017-11-17 00:45
Closing because we still haven't any idea how to deal with this, and it's not relevant to the issue.

**Closed by hcayless** 2017-11-17 00:45 UTC
Labels: bug, CouncilResponsibility, status:needs discussion
