### ISSUE TITLE
Need to make deletion of `<defaultVal>` work

### ISSUE THREAD

**Issue by martindholmes** [TEIC/Stylesheets#393] opened 2019-09-13 20:20 UTC
Following the implementation of https://github.com/TEIC/TEI/issues/1807, we need to add whatever processing is needed to make `@mode` work on the `<defaultVal>` element. The primary use-case is delete, but we should also decide if there's going to be any difference between `@mode='replace'` and `@mode="change"` on this element, and if so, what it is (I don't see how there could be a difference myself, but we'll see), and then add processing as required.

**Comment by martindholmes** [comment] 2019-10-24 15:35
@sydb and me, prepping for the Stylesheets meeting, believe that the choose element starting here:

https://github.com/TEIC/Stylesheets/blob/dev/odds/odd2odd.xsl#L1763

is the place where the change needs to be made. It looks like the only thing that needs to be done is to implement the delete, since the use of the justcopy mode on the `$New` element would probably do the right thing for a replace or a change, but this needs to be tested.

**Comment by sydb** [comment] 2019-10-24 17:24
[Here](https://github.com/TEIC/Stylesheets/files/3768703/test_defaultVal.odd.txt) is a little test ODD customization file we can use for testing. Currently the output is invalid RELAX NG due to duplicated defentions of the attribute patterns.

**Comment by martindholmes** [comment] 2019-11-05 15:05
It turns out the test ODD was wrong; it was missing `@mode="change"` on the ancestor attDef elements. Here's a fixed one.
[test_defaultVal_and_code_in_desc.odd.txt](https://github.com/TEIC/Stylesheets/files/3809597/test_defaultVal_and_code_in_desc.odd.txt)

This gives us a valid RELAX NG file, but the next thing is to test whether all the modes are working correctly.

**Comment by ebeshero** [comment] 2019-11-05 16:02
We were able to solve this particular ticket by amending the test ODD file, though it leads us to contemplate a larger issue regarding whether such amendments should be necessary. We're closing this ticket and opening a new one: #402 .

**Comment by sydb** [comment] 2019-11-05 16:32
> It turns out the test ODD was wrong; it was missing `@mode="change"` on the ancestor attDef elements.

For the record, I do not think this (not having `@mode` on the parent `<attDef>`) is wrong, because it is on the ancestor `<elementSpec>`. That is, I think the `@mode` on `<attDef>` is supposed to be optional, and the Stylesheets should do the right thing if it is missing.
I am quite confident that the original intent was that the value of `@mode` would be inherited. (From the closest ancestor with a `@mode` attribute — i.e., the mode of a combinable element is `ancestor-or-self::*[@mode][1]/@mode`.) However, in a quick scan I do not find any documentation in the _Guidelines_ to back this up.
Hence ticket #402.

**Comment by martindholmes** [comment] 2019-11-05 16:34
I don't think we can close this ticket until we confirm that what we intended by the test ODD was actually accomplished. We know we have a valid ODD, but as far as I know, `@mode="delete|change|add|replace"` may not do anything at all.

**Comment by hcayless** [comment] 2019-11-05 17:14
I've tested them, and they all seem to do what I'd expect. I do notice that `<defaultVal mode="add">foo</defaultVal>` and `<defaultVal mode="add">foo</defaultVal>` have the same result, which is maybe to be expected... Perhaps part of the problem is that the semantics of `@mode` depend on where it's applied... I'm in favor of closing this issue unless there are strong objections.

**Comment by martindholmes** [comment] 2019-11-08 17:31
@hcayless Your comment above confused @sydb and me a bit -- you have `<defaultVal mode="add">foo</defaultVal>` twice. Do you mean "change" and "add", or "replace" and "add"? At any rate, if you're sure the current behaviour does allow the deletion of `<defaultVal>`, then do close. See #402 for follow-up work.

**Comment by hcayless** [comment] 2019-11-08 17:53
@martindholmes copy-paste error, sorry. I meant that you don't need a `@mode="add"` to get the result of adding a defaultVal—the `@mode="change"` on the parent is sufficient. Closing.

**Closed by hcayless** 2019-11-08 17:53 UTC
Labels: CouncilResponsibility, High Priority, enhancement, status:Consider4StylesheetsGroup, status:needs discussion
