### ISSUE TITLE
handle defaultVal/@validUntil

### ISSUE THREAD

**Issue by sydb** [TEIC/Stylesheets#158] opened 2016-06-10 15:55 UTC
When [Guidelines ticket #1467](https://github.com/TEIC/TEI/issues/1467) is implemented, we need to test that a `@validUntil` attribute on a `<defaultVal>` will generate a red box on tagdoc creation, and if not, make it so.

**Comment by martindholmes** [comment] 2016-06-18 22:02
After trying my best to read the Stylesheets, specifically common/common_tagdocs.xsl, it's my belief that `@validUntil` on `<defaultVal>` is NOT handled in the output, but I think the simplest way to prove it is to try it, so I propose to test-implement https://github.com/TEIC/TEI/issues/1467 and see what Mr Jenkins produces, then reverse the implementation.

**Comment by martindholmes** [comment] 2016-06-18 23:27
Confirmed: There is no handling in the Stylesheets for `@validUntil` on `<defaultVal>`.

**Comment by martindholmes** [comment] 2016-07-22 16:37
Syd and I have implemented the handling of `defaultVal[@validUnti]`, which is not quite as straightforward as we had hoped. We had to call the "validUntil" templates from the tei:defaultVal template, but we also had to tweak both templates, because the expectation of the existing code was that `@validUntil` was on an element which created in the output a complete table row; in the case of `<defaultVal>`, the context for the output is actually a cell, so we had to create an additional table to contain the deprecation comment. We also added a special new message customized for the `<defaultVal>` context to the Stylesheets i18n.xml file (a file full of text strings used in generating output), because the standard deprecation message was a bit ambiguous in the context of `<defaultVal>`. That message will need to be translated at some point (although most languages lack translations for most messages at the moment anyway).

**Comment by martindholmes** [comment] 2016-07-22 16:54
In our first pass, we just handled the case where there's no valList; we've also modified the template `@name="valListItems"` to add similar explicit handling for `defaultVal/@validUntil`, since `<defaultVal>` is handled there rather than in its own template for these cases.

**Comment by martindholmes** [comment] 2016-07-22 17:06
Changes committed in 
https://github.com/TEIC/Stylesheets/commit/6d80c743ecbaed689d7f212536da2e1382f8ef4e
Waiting to see if they build correctly.

**Comment by martindholmes** [comment] 2016-07-29 16:17
We have identified some minor variations in the way the deprecation information is displayed: specifically, when the deprecated defaultVal is one of a set of valItems defined in the attDef, then the deprecation message lacks the link on the word "Deprecated" pointing to TCW27; but when the defaultVal is supplied but the datatype is responsible for providing the value set (no valList), the deprecation message is better formatted and rendered. Examples showing this are:

http://teijenkins.hcmc.uvic.ca/job/TEIP5-dev/lastSuccessfulBuild/artifact/P5/release/doc/tei-p5-doc/en/html/ref-availability.html 
(defaultVal is part of a valList)

http://teijenkins.hcmc.uvic.ca/job/TEIP5-dev/lastSuccessfulBuild/artifact/P5/release/doc/tei-p5-doc/en/html/ref-sound.html 
(defaultVal is in addition to data.xTruthValue)

We need to align the two styles of representation, with the way the latter appears as the preferred one.

There are similar issues in the ePub, which may well be resolved by fixes which take care of the HTML. The situation in the PDF is far worse, with the entire attribute representation for these two attributes being completely different; this is a much bigger problem that needs its own ticket when we have a LaTeX expert available.

**Comment by lb42** [comment] 2016-07-29 16:24
The wording "[Default. The default value will be removed after 2017-09-05.]" seems a bit misleading, especially in context. The value itself won't be removed from the list of legal values will it? Just its "defaultness". So it will remain a legal value, and should stay in the valList.

**Comment by martindholmes** [comment] 2016-07-29 16:26
Lou, you're right that the message is misleading. We can easily change that. "The value will no longer be a default after date XXX."

**Comment by martindholmes** [comment] 2016-08-26 16:32
Message changed in commit 2361b79..89c45d2.

**Comment by martindholmes** [comment] 2016-12-09 18:20
Syd and I worked on this and we think we've fixed it in https://github.com/TEIC/Stylesheets/commit/bfaa9f8940589e91bfa887b5688c75441bb7869a.

**Comment by martindholmes** [comment] 2016-12-09 22:03
Our attempted fix seems to have broken the build. Added an attempted fix in https://github.com/TEIC/Stylesheets/commit/c44a2fc250b575d82b6c5ad8cf214df65a84223a.

**Comment by martindholmes** [comment] 2016-12-13 00:19
Judging by the results in the upcoming release branch:

http://teijenkins.hcmc.uvic.ca/job/TEIP5-release-3.1.0/lastSuccessfulBuild/artifact/P5/release/doc/tei-p5-doc/en/html/ref-availability.html
http://teijenkins.hcmc.uvic.ca/job/TEIP5-release-3.1.0/lastSuccessfulBuild/artifact/P5/release/doc/tei-p5-doc/en/html/ref-constraintSpec.html
http://teijenkins.hcmc.uvic.ca/job/TEIP5-release-3.1.0/lastSuccessfulBuild/artifact/P5/release/doc/tei-p5-doc/en/html/ref-sound.html

we have completed this successfully. Closing the ticket.

**Closed by martindholmes** 2016-12-13 00:19 UTC
Labels: bug, CouncilResponsibility
