### ISSUE TITLE
inconsistent wrapping in lines for CO chapter

### ISSUE THREAD

**Issue by kshawkin** [TEIC/Stylesheets#162] opened 2016-07-24 21:07 UTC
As someone wrote to web@tei-c.org:

> The CSS on http://www.tei-c.org/release/doc/tei-p5-doc/en/html/CO.html is causing there to be horizontal scrolling, which is not true of other pages on the site. I tried to figure out what the problem was, but I couldn’t.

I've looked at the ODD source to see if there's a difference in line breaks or tagging, but I can't figure out what's causing it either.

**Comment by martindholmes** [comment] 2016-07-25 00:29
It's the unwrapped example at the end of 3.6. I'll fix it.

**Comment by martindholmes** [comment] 2016-07-25 00:36
I've also taken the opportunity to change the SourceForge URL in the example to the equivalent GitHub location. If it builds OK and the problem is fixed on Jenkins, we can close the ticket.

**Comment by kshawkin** [comment] 2016-07-25 01:15
There seem to be others that don't wrap as well: see one in http://www.tei-c.org/release/doc/tei-p5-doc/en/html/CO.html#CONARS .

**Comment by martindholmes** [comment] 2016-07-25 03:44
That didn't actually fix it:

http://teijenkins.hcmc.uvic.ca/job/TEIP5-dev/lastSuccessfulBuild/artifact/P5/release/doc/tei-p5-doc/en/html/CO.html

There's another even worse one in 3.5.1. I've fixed that one. We'll keep going until we've got them all. It's difficult to predict from the source what the wrap will end up as in the output.

**Comment by lb42** [comment] 2016-07-25 09:00
This is a recurrent problem. Maybe worth updating tcw20 to remind people to check that modifications made to examples in the text don't break the HTML formatting ?

**Comment by martindholmes** [comment] 2016-07-25 12:28
Trying a third fix this morning.

**Comment by martindholmes** [comment] 2016-07-25 12:41
@lb42: actually we need to look at the Stylesheets code that handles the formatting of examples and tweak it a bit. It's notoriously hard to format egXMLs in a way that gives consistently good results, and this particular algorithm has problems with a couple of specific things (in this case, I think, an egXML consisting of a `<p>` whose entire content is a `<q>`). Right now I can't even predict where this problem will occur with any consistency without building the chapter and looking at the results. I've written this sort of rendering code twice myself, once in the CodeSharing thing and once for the Map of London project, and I've never found a perfect way to do it yet. You have to strike a balance between some degree of auto-formatting to avoid extra-long lines and the need to allow example writers to add breaks where they think they should occur for the purposes of the example; and you have to make some assumptions about which elements are usually inline and which are usually blocks which often turn out to be wrong for specific examples.

**Comment by lb42** [comment] 2016-07-25 12:47
No harm in looking at it again certainly but I do know that Sebastian repeatedly spent ages tweaking that particukar bit of code. My point was simply to remind council members to to be careful when modifying existing examples. If we can identify a small set of specific cases which cause this problem that would certainly be helpful.

**Comment by martindholmes** [comment] 2016-07-25 15:01
That specific example:

http://teijenkins.hcmc.uvic.ca/job/TEIP5/lastSuccessfulBuild/artifact/P5/release/doc/tei-p5-doc/en/html/CO.html#index-egXML-d50e34949

is particularly evil. I've had two shots at it and failed. I think we'll have to look at the Stylesheets code.

**Comment by lb42** [comment] 2016-07-25 18:05
Have you tried removing the redundant &lt;p> ?

**Comment by martindholmes** [comment] 2016-07-25 19:20
No, I assumed I shouldn't mess with the content of an example just to fix a formatting issue. If you think it's fine to do that, go ahead.

**Comment by martindholmes** [comment] 2016-07-26 00:00
Removed the `<p>`, since now I look at it, it's irrelevant, as you rightly point out. Let's see...

**Comment by lb42** [comment] 2016-07-26 08:21
Looking back through previous versions of the gl shows that this example has been a bastard since at least 2.0 ...

**Comment by martindholmes** [comment] 2016-07-26 12:31
Seems to be fixed now, after removing the `<p>`. But I can't quite figure out how the preceding examples using the same text and virtually the same encoding were never afflicted.

http://teijenkins.hcmc.uvic.ca/job/TEIP5-dev/lastSuccessfulBuild/artifact/P5/release/doc/tei-p5-doc/en/html/CO.html#COXR

We should leave this ticked open, and at some point revert the last commit on a branch, and try to make a Stylesheet change that fixes it.

**Comment by martindholmes** [comment] 2016-12-13 00:34
I had another thought about this: we could add a Schematron rule which catches long unbroken lines in text nodes inside egXML. I'm going to experiment with this. The only possible drawback I can see is that we'd be constraining the content of examples purely to avoid issues with our own rendering output, whereas arguably the rendering process ought to handle the problem, and the Schematron rule might be annoying for other encoders who've successfully written rendering processes that handle the issue, so they don't need to tweak their egXML text nodes. But it would prevent new instances of the same issue getting through into a Guidelines release.

**Comment by martindholmes** [comment] 2016-12-13 01:00
The relevant code is in common/verbatim.xsl, starting on l. 148. The $forceWrap parameter is false by default; it seems to me that it should be true so that the verbatim-reformatText recursive function would get called. But the very first xsl:when looks wrong to me; it seems to say that if the text node is a direct child of an egXML, it should be output directly with all spaces converted to non-breaking. Why?

**Comment by martindholmes** [comment] 2016-12-13 01:35
The only example that can be made to exhibit the problem in that chapter currently is this one:

http://teijenkins.hcmc.uvic.ca/job/TEIP5-dev/lastSuccessfulBuild/artifact/P5/release/doc/tei-p5-doc/en/html/CO.html#index-egXML-d52e43897

if you make the window really small. But that example is a mess anyway -- needs a separate ticket...

**Comment by martindholmes** [comment] 2018-01-21 23:08
I'm closing this because none of the existing egXMLs seem to exhibit the problem. Easier to fix an instance when it occurs in the source code than revisit the gnarly egXML processing.

**Closed by martindholmes** 2018-01-21 23:08 UTC
Labels: bug, status:in progress
